name: tagged-action

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  action-if-tagged:
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Check if ref is tag
        run: |
          echo "refにブランチが指定されました。タグを指定してください。" >> $GITHUB_STEP_SUMMARY
          exit 1

  call-workflow:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      ref_name: ${{ github.ref_name }}