name: tagged-action

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  check-ref-type:
    runs-on: ubuntu-latest
    steps:
      - name: Check if ref is tag
        if: github.ref_type != 'tag'
        run: |
          echo "refにブランチが指定されました。タグを指定してください。" 1>&2
          exit 1

  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: echo github.ref_name
        run: |
          echo github ref_nameは${{ github.ref_name }}