on:
  pull_request:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest

    steps:
      - name: sample
        uses: actions/github-script@v6
        with:
          script: |
            const devList = [
              'dev11',
              'dev12',
              'dev21',
              'dev22',
            ]
            
            const output = devList.map(dev => {
              return `
              <details><summary>${dev}</summary>
              
              \`\`\`shell
              echo 'hello world'
              \`\`\`
              </details>
              `
            }).join('')
            
            await core.summary
              .addHeading('sample', 2)
              .addRaw(output)
              .write()
