on:
  pull_request:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest

    steps:
      - name: sample
        uses: actions/github-script@v6
        with:
          script: |
            const output = `
            <details><summary>dev11</summary>

            \`\`\`shell
            echo 'hello world'
            \`\`\`
            </details>
            <details><summary>dev12</summary>
            `
            
            await core.summary
              .addHeading('sample', 2)
              .write()
