on:
  pull_request:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest

    steps:
      - name: sample
        uses: actions/github-script@v6
        with:
          script: |
            const output1 = `
            \`aaa\`を\`bbb\`する
            \`\`\`shell
            gh workflow run hogehoge
            \`\`\`
            `
            const output2 = `gh workflow run hogehoge`
            
            await core.summary
              .addHeading('sample', 2)
              .addRaw(output1)
              .addHeading('sample2', 2)
              .addCodeBlock(output2)
              .write()
