on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

env:
  branch_name: ${{ github.head_ref || github.ref_name }}
  revision: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  sample:
    runs-on: ubuntu-latest

    steps:
      - name: sample
        uses: actions/github-script@v6
        with:
          script: |
            echo "aaaaa"
            echo ${{ env.branch_name }}
            echo ${{ env.revision }}
