on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest

    steps:
      - name: sample
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = "
            <details><summary>dev11</summary>

            ```shell
            echo 'hello world'
            ```
            </details>
            <details><summary>dev12</summary>
            
            await core.summary
              .addHeading('sample', 2)
              .addCodeBlock(output)
              .write()
